import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      about: 'About',
      projects: 'Projects',
      skills: 'Skills',
      contact: 'Contact',
    },
    hero: {
      greeting: "Hello, I'm",
      name: 'Abdulaziz Alhaidan',
      title: 'AI / Machine Learning Engineer',
      titles: ['AI / ML Engineer', 'LLM & Multi-Agent Systems', 'RAG & GenAI Engineer', 'Backend Engineer'],
      bio: "AI / Machine Learning Engineer who designs, builds, and ships production-grade LLM and ML systems end-to-end — from data and training to RAG pipelines, multi-agent orchestration, and deployment. Focused on trustworthy, Arabic-first AI for the Saudi market.",
      cta1: 'Talk to Aime',
      cta2: 'View Projects',
      cta3: 'Download CV',
      available: 'Available for opportunities',
    },
    about: {
      title: 'About Me',
      p1: "AI / Machine Learning Engineer with a B.Sc. in Computer Science who builds and ships production-grade LLM and ML systems end-to-end. I won 1st place at the Himmah Digital Camps hackathon for AI Board Room — a multi-agent executive-advisory system — and independently designed, built, and launched Hanak, an Arabic-first review platform now live in production.",
      p2: "My edge is Arabic-first, production-ready AI: LLM integration (OpenAI, Azure OpenAI, Anthropic Claude), multi-agent orchestration, RAG pipelines built from scratch, embeddings, and vector databases — served through reliable FastAPI backends and deployed to the cloud. I've led a four-person engineering team across data, training, and deployment, and I build with responsible-AI practices from day one.",
      education: 'Education',
      university: 'Majmaah University — College of Sciences, Zulfi',
      degree: 'Bachelor of Computer Science',
      gpa: 'GPA: 4.01 / 5 — Very Good',
      period: '2020 – 2025',
      certifications: 'Certifications',
      certs: [
        { name: 'IBM Data Science Professional Certificate', issuer: 'IBM / Coursera', year: '2025' },
        { name: 'TensorFlow Developer Specialization', issuer: 'DeepLearning.AI', year: '2025' },
        { name: 'AWS Cloud Practitioner Essentials (course)', issuer: 'Amazon Web Services', year: '2025' },
      ],
    },
    experience: {
      title: 'Experience',
      current: 'Current',
      items: [
        {
          role: 'AI Engineering Bootcamp',
          org: 'Saudi Digital Academy (SDA)',
          period: 'May 2026 – Jul 2026',
          current: false,
          points: [
            'End-to-end ML pipelines: EDA, feature engineering, hyperparameter tuning, and rigorous error analysis.',
            'CNNs, RNN/LSTM, Seq2Seq, and time-series models; fine-tuned BERT with Hugging Face.',
            'Built a complete RAG system from scratch (embeddings + FAISS); advanced prompt engineering with DSPy/GEPA.',
            'Production packaging: ONNX export, serialization, and MLflow experiment tracking.',
          ],
        },
        {
          role: 'Cooperative Training — Quality Assurance',
          org: 'T2 — Riyadh, Saudi Arabia',
          period: 'Feb 2025 – May 2025',
          current: false,
          points: [
            'Designed and executed functional and regression test suites across releases.',
            'Tracked defects to resolution and validated fixes before sign-off.',
            'Built a systematic approach to failure-case and edge-case analysis — the same discipline now applied to evaluating model outputs.',
          ],
        },
      ],
    },
    projects: {
      title: 'Projects',
      live: 'Live',
      docs: 'Docs',
      github: 'GitHub',
      moreTitle: 'More Projects',
      items: [
        {
          id: 'board-room',
          name: 'AI Board Room',
          award: '1st Place — Himmah Digital Camps',
          awardIcon: 'trophy',
          desc: 'Multi-agent system that simulates a corporate advisory board: CFO, Legal Advisor, and Market Strategist agents deliberate, vote, and reach consensus synthesized by a Chairman agent — each grounded in company documents through a FAISS RAG layer.',
          tags: ['Python', 'LangChain', 'Multi-Agent', 'FAISS', 'FastAPI', 'React'],
          live: 'https://ai-board-room-2wtb.onrender.com/',
          github: 'https://github.com/AbdulazizCsDev/ai-board-room',
        },
        {
          id: 'aime',
          name: 'Aime Voice Assistant',
          award: null,
          desc: "Production-deployed Arabic-first AI voice assistant: Whisper (speech-to-text), Claude (reasoning), and ElevenLabs (voice cloning), served through FastAPI and grounded in a curated knowledge base. You're chatting with it live on this site.",
          tags: ['Python', 'FastAPI', 'Whisper', 'Claude', 'ElevenLabs'],
          live: 'https://aime-voice-assistant-rw2z.vercel.app/',
          github: 'https://github.com/AbdulazizCsDev/aime-voice-assistant',
        },
        {
          id: 'agrocure',
          name: 'AgroCure — Plant Disease Detection',
          award: 'Led a 4-person team',
          awardIcon: 'team',
          desc: 'End-to-end plant-disease classification (ResNet50 transfer learning, 36+ classes, ~7,300 images) with a RAG advisory layer for rare classes and a custom in-house dataset. Served as a public inference API on Hugging Face Spaces (FastAPI + Docker); experiments tracked with MLflow on DagsHub.',
          tags: ['PyTorch', 'ResNet50', 'FAISS', 'MLflow', 'Docker'],
          live: 'https://abdulazizcsdev-agrocure-app.hf.space/',
          github: 'https://github.com/AbdulazizCsDev/AgriCure-App',
        },
        {
          id: 'hanak',
          name: 'Hanak — Arabic Restaurant Reviews',
          award: null,
          desc: 'Arabic-first restaurant review platform, designed and shipped end-to-end from concept to live release. Postgres on Supabase with trigram (pg_trgm) fuzzy search over Arabic venue names and SECURITY DEFINER policies for admin operations; each restaurant\'s menu is the canonical unit, so reviews stay attributed across branches and name variants.',
          tags: ['Next.js', 'Supabase', 'PostgreSQL', 'Vercel'],
          live: 'https://hanak-rosy.vercel.app/',
          github: null,
        },
        {
          id: 'lines',
          name: 'Between the Lines',
          award: null,
          desc: 'AI-powered X archive analyzer that reveals hidden engagement patterns and turns them into a ready-to-execute content strategy. ZIP parsing runs fully in-browser — your data never leaves your device.',
          tags: ['Next.js', 'React', 'FastAPI', 'Claude AI', 'SQLite', 'Tailwind CSS'],
          live: 'https://x-tweets-analyzer.vercel.app/',
          github: 'https://github.com/AbdulazizCsDev/x-tweets-analyzer',
        },
        {
          id: 'forecast',
          name: 'Weather-Driven Demand Forecasting',
          award: null,
          desc: 'End-to-end ML pipeline forecasting car wash demand in Riyadh from live weather data, served through a FastAPI REST API. Reduced prediction MAE by ~50%.',
          tags: ['Python', 'FastAPI', 'Scikit-learn', 'REST APIs', 'SQL'],
          live: null,
          github: 'https://github.com/AbdulazizCsDev/carwash-demand-forecast',
        },
      ],
      more: [
        {
          id: 'carwash',
          name: 'Car Wash Management System',
          desc: 'Full-stack management platform with role-based access, real-time order tracking, and payment integration. Graduation project.',
          tags: ['Flutter', 'PHP', 'MySQL'],
          live: null,
          docs: 'https://car-wash-system-b7mamo4.gamma.site/',
          github: 'https://github.com/AbdulazizCsDev/carwash_system',
        },
        {
          id: 'spy',
          name: 'Online Multiplayer Spy Game',
          desc: 'Real-time multiplayer party game with room management, voting, and reconnection handling.',
          tags: ['React', 'Node.js', 'Socket.IO'],
          live: 'https://typing-game-client.onrender.com/',
          github: 'https://github.com/AbdulazizCsDev/typing-game',
        },
      ],
    },
    skills: {
      title: 'Skills',
      categories: [
        {
          name: 'GenAI & LLMs',
          icon: 'bot',
          skills: ['LLM Integration (OpenAI, Azure OpenAI, Claude)', 'Multi-Agent Orchestration', 'RAG (built from scratch)', 'LangChain', 'FAISS', 'ChromaDB', 'Embeddings', 'Prompt Engineering (DSPy/GEPA)', 'Fine-tuning', 'Hugging Face', 'BERT'],
        },
        {
          name: 'ML & Deep Learning',
          icon: 'network',
          skills: ['PyTorch', 'TensorFlow', 'Scikit-learn', 'CNNs / Transfer Learning', 'RNN / LSTM / Seq2Seq', 'Time-Series Forecasting', 'Evaluation & Diagnostics'],
        },
        {
          name: 'MLOps & Deployment',
          icon: 'rocket',
          skills: ['MLflow', 'ONNX', 'FastAPI Model Serving', 'Docker', 'CI/CD', 'Cloud Deployment (HF Spaces, Railway, Render, Vercel)', 'Azure (AI Foundry, OpenAI)', 'AWS (IAM, EC2, S3)'],
        },
        {
          name: 'Backend & APIs',
          icon: 'server',
          skills: ['Python', 'FastAPI', 'Flask', 'REST APIs', 'Node.js'],
        },
        {
          name: 'Databases',
          icon: 'database',
          skills: ['SQL', 'PostgreSQL (Supabase)', 'MySQL', 'Vector Databases', 'Database Design'],
        },
        {
          name: 'Frontend & Mobile',
          icon: 'layout',
          skills: ['React.js', 'Next.js', 'HTML', 'CSS', 'Socket.IO', 'Flutter', 'Dart'],
        },
        {
          name: 'Practices & Languages',
          icon: 'code',
          skills: ['Responsible AI / AI Ethics', 'Git & Version Control', 'Arabic (Native)', 'English (Advanced)'],
        },
      ],
    },
    contact: {
      title: "Let's Connect",
      subtitle: "I'm always open to new opportunities, collaborations, and interesting conversations.",
      email: 'Email',
      linkedin: 'LinkedIn',
      github: 'GitHub',
      emailVal: 'abdulaziz.alhaidan.cs@gmail.com',
      linkedinVal: 'www.linkedin.com/in/abdulaziz-alhaidan-a902b4232/',
      githubVal: 'github.com/AbdulazizCsDev',
    },
    aime: {
      placeholder: 'Ask Aime anything...',
      hold: 'Hold to speak',
      greeting: "Hi! I'm Aime, Abdulaziz's AI assistant. I can tell you about his work, projects, and skills — or run a job-fit check if you're hiring. How can I help you today?",
      bubbleGreet: "Hi there! Need help? I can tell you about Abdulaziz's work!",
      release: 'Release to send...',
      online: 'Online',
      listening: 'Listening...',
      thinking: 'Thinking...',
      noBackend: "Sorry, I couldn't connect to the backend right now.",
      noTranscribe: "Couldn't transcribe the audio. Please try again.",
      suggestions: [
        { label: 'Quick tour', icon: 'target', tour: true },
        {
          label: 'Projects',
          query: 'What are his projects?',
          canned: 'These are his projects — any specific one you want to dig into?',
          action: 'projects',
        },
        { label: 'Hackathon Win', icon: 'trophy', query: 'Tell me about the AI Board Room hackathon win' },
        { label: 'Job Fit Check', query: "I'm a recruiter. I'll paste a job description, and I want you to analyze how well Abdulaziz fits it — matched skills, which of his projects prove each requirement, and honest gaps. Ready?" },
        {
          label: 'Contact',
          query: 'How can I contact him?',
          canned: "Here's how to reach him — email or LinkedIn work best. Anything else you'd like to know first?",
          action: 'contact',
        },
      ],
      tour: [
        { text: "Let me show you around. This is Abdulaziz — an AI/ML engineer who designs, builds, and ships LLM and ML systems end-to-end.", action: 'about' },
        { text: 'His projects. Start with AI Board Room — a multi-agent advisory board that took 1st place at the Himmah Digital Camps hackathon.', action: 'projects.board-room' },
        { text: 'AgroCure — plant-disease detection across 36+ classes, served live on Hugging Face Spaces. He led the four-person team behind it.', action: 'projects.agrocure' },
        { text: "And Aime — that's me: Whisper, Claude, and ElevenLabs, deployed and chatting with you right now.", action: 'projects.aime' },
        { text: 'The toolkit behind it all — GenAI, deep learning, and MLOps.', action: 'skills' },
        { text: "And this is where to reach him. Ask me anything else — I'm here.", action: 'contact' },
      ],
    },
  },
  ar: {
    nav: {
      about: 'عني',
      projects: 'المشاريع',
      skills: 'المهارات',
      contact: 'تواصل',
    },
    hero: {
      greeting: 'مرحباً، أنا',
      name: 'عبدالعزيز الحيدان',
      title: 'مهندس ذكاء اصطناعي وتعلّم آلة',
      titles: ['مهندس ذكاء اصطناعي / تعلّم آلة', 'أنظمة LLM والوكلاء المتعددين', 'مهندس RAG وذكاء توليدي', 'مهندس باك إند'],
      bio: 'مهندس ذكاء اصطناعي وتعلّم آلة أصمّم وأبني وأطلق أنظمة LLM وتعلّم آلة بجودة إنتاجية من البداية إلى النهاية — من البيانات والتدريب إلى RAG وتنسيق الوكلاء المتعددين والنشر. أركّز على ذكاء اصطناعي موثوق يتحدث العربية أولاً للسوق السعودي.',
      cta1: 'تحدث مع آيم',
      cta2: 'عرض المشاريع',
      cta3: 'تحميل السيرة الذاتية',
      available: 'متاح للفرص المهنية',
    },
    about: {
      title: 'عني',
      p1: 'مهندس ذكاء اصطناعي وتعلّم آلة حاصل على بكالوريوس علوم الحاسب، أبني وأطلق أنظمة LLM وتعلّم آلة بجودة إنتاجية من البداية إلى النهاية. فزت بالمركز الأول في هاكاثون معسكرات همّة الرقمية عن «مجلس الإدارة الذكي» — نظام استشاري تنفيذي متعدد الوكلاء — وصمّمت وبنيت وأطلقت وحدي «Hanak»، منصة تقييمات عربية أولاً تعمل الآن في بيئة الإنتاج.',
      p2: 'ما يميزني هو الذكاء الاصطناعي الإنتاجي بالعربية أولاً: دمج نماذج اللغة الكبيرة (OpenAI وAzure OpenAI وClaude من Anthropic)، وتنسيق الوكلاء المتعددين، وبناء أنظمة RAG من الصفر مع التضمينات وقواعد البيانات المتجهة — تُقدَّم عبر واجهات FastAPI موثوقة وتُنشر على السحابة. قُدت فريقاً هندسياً من أربعة أشخاص عبر البيانات والتدريب والنشر، وأبني وفق ممارسات الذكاء الاصطناعي المسؤول منذ اليوم الأول.',
      education: 'التعليم',
      university: 'جامعة المجمعة — كلية العلوم، الزلفي',
      degree: 'بكالوريوس علوم الحاسب',
      gpa: 'المعدل: 4.01 / 5 — جيد جداً',
      period: '2020 – 2025',
      certifications: 'الشهادات',
      certs: [
        { name: 'شهادة IBM لعلوم البيانات', issuer: 'IBM / Coursera', year: '2025' },
        { name: 'تخصص TensorFlow للمطورين', issuer: 'DeepLearning.AI', year: '2025' },
        { name: 'أساسيات السحابة — AWS (دورة)', issuer: 'أمازون ويب سيرفيسز', year: '2025' },
      ],
    },
    experience: {
      title: 'الخبرات',
      current: 'حالياً',
      items: [
        {
          role: 'معسكر هندسة الذكاء الاصطناعي',
          org: 'الأكاديمية السعودية الرقمية (SDA)',
          period: 'مايو 2026 – يوليو 2026',
          current: false,
          points: [
            'خطوط أنابيب تعلّم آلة متكاملة: تحليل استكشافي، هندسة خصائص، ضبط معاملات، وتحليل دقيق للأخطاء.',
            'شبكات CNN وRNN/LSTM وSeq2Seq ونماذج سلاسل زمنية؛ وضبط دقيق لـ BERT عبر Hugging Face.',
            'بناء نظام RAG كامل من الصفر (تضمينات + FAISS)؛ وهندسة موجهات متقدمة بـ DSPy/GEPA.',
            'تجهيز النماذج للإنتاج: تصدير ONNX، والتسلسل، وتتبع التجارب بـ MLflow.',
          ],
        },
        {
          role: 'تدريب تعاوني — ضمان الجودة',
          org: 'T2 — الرياض، السعودية',
          period: 'فبراير 2025 – مايو 2025',
          current: false,
          points: [
            'تصميم وتنفيذ حزم اختبارات وظيفية واختبارات انحدار عبر الإصدارات.',
            'تتبّع العيوب حتى إغلاقها والتحقق من الإصلاحات قبل الاعتماد.',
            'بناء منهجية منظّمة لتحليل حالات الفشل والحالات الحدّية — الانضباط نفسه الذي أطبّقه اليوم في تقييم مخرجات النماذج.',
          ],
        },
      ],
    },
    projects: {
      title: 'المشاريع',
      live: 'مباشر',
      docs: 'التوثيق',
      github: 'جيت هاب',
      moreTitle: 'مشاريع أخرى',
      items: [
        {
          id: 'board-room',
          name: 'مجلس الإدارة الذكي — AI Board Room',
          award: 'المركز الأول — معسكرات همّة الرقمية',
          awardIcon: 'trophy',
          desc: 'نظام متعدد الوكلاء يحاكي مجلساً استشارياً تنفيذياً: وكلاء متخصصون (مدير مالي، مستشار قانوني، خبير سوق) يتداولون ويصوّتون ويصلون إلى توصية موحّدة يصوغها وكيل «رئيس المجلس» — مع تأصيل كل رأي في وثائق الشركة عبر طبقة RAG بـ FAISS.',
          tags: ['Python', 'LangChain', 'Multi-Agent', 'FAISS', 'FastAPI', 'React'],
          live: 'https://ai-board-room-2wtb.onrender.com/',
          github: 'https://github.com/AbdulazizCsDev/ai-board-room',
        },
        {
          id: 'aime',
          name: 'آيم — المساعد الصوتي',
          award: null,
          desc: 'مساعد صوتي ذكي منشور إنتاجياً يدعم العربية أولاً: Whisper لتحويل الصوت إلى نص، وClaude للاستدلال، وElevenLabs لاستنساخ الصوت، يُقدَّم عبر FastAPI وإجاباته مؤصّلة في قاعدة معرفة منتقاة. أنت تحادثه الآن على هذا الموقع.',
          tags: ['Python', 'FastAPI', 'Whisper', 'Claude', 'ElevenLabs'],
          live: 'https://aime-voice-assistant-rw2z.vercel.app/',
          github: 'https://github.com/AbdulazizCsDev/aime-voice-assistant',
        },
        {
          id: 'agrocure',
          name: 'أجروكيور — كشف أمراض النباتات',
          award: 'قيادة فريق من 4 مهندسين',
          awardIcon: 'team',
          desc: 'نظام متكامل لتصنيف أمراض النباتات (ResNet50 بنقل التعلم، +36 صنفاً، ~7,300 صورة) مع طبقة RAG استشارية للأصناف النادرة وبيانات مجمّعة ومصنّفة داخلياً. يُقدَّم كواجهة استدلال عامة على Hugging Face Spaces (FastAPI + Docker)؛ مع تتبع التجارب بـ MLflow على DagsHub.',
          tags: ['PyTorch', 'ResNet50', 'FAISS', 'MLflow', 'Docker'],
          live: 'https://abdulazizcsdev-agrocure-app.hf.space/',
          github: 'https://github.com/AbdulazizCsDev/AgriCure-App',
        },
        {
          id: 'hanak',
          name: 'Hanak — منصة عربية لتقييم المطاعم',
          award: null,
          desc: 'منصة تقييمات مطاعم بالعربية أولاً، صمّمتها وأطلقتها من الفكرة حتى الإطلاق الفعلي. قاعدة Postgres على Supabase مع بحث تقريبي بالـ trigram (pg_trgm) على أسماء المطاعم العربية، وسياسات SECURITY DEFINER لعمليات الإدارة؛ وقائمة طعام كل مطعم هي الوحدة المرجعية، فتبقى التقييمات منسوبة بدقة عبر الفروع واختلاف الأسماء.',
          tags: ['Next.js', 'Supabase', 'PostgreSQL', 'Vercel'],
          live: 'https://hanak-rosy.vercel.app/',
          github: null,
        },
        {
          id: 'lines',
          name: 'بين السطور — محلل أرشيف X',
          award: null,
          desc: 'محلل ذكي لأرشيف X يكشف أنماط التفاعل المخفية ويحوّلها إلى استراتيجية محتوى جاهزة للتنفيذ. معالجة الملفات تتم بالكامل داخل المتصفح — بياناتك لا تغادر جهازك.',
          tags: ['Next.js', 'React', 'FastAPI', 'Claude AI', 'SQLite', 'Tailwind CSS'],
          live: 'https://x-tweets-analyzer.vercel.app/',
          github: 'https://github.com/AbdulazizCsDev/x-tweets-analyzer',
        },
        {
          id: 'forecast',
          name: 'التنبؤ بالطلب المرتبط بالطقس',
          award: null,
          desc: 'نظام تعلّم آلة متكامل يتنبأ بالطلب على غسيل السيارات في الرياض من بيانات الطقس الحية، ويُقدَّم عبر واجهة FastAPI. خفّض خطأ التنبؤ بنسبة ~50%.',
          tags: ['Python', 'FastAPI', 'Scikit-learn', 'REST APIs', 'SQL'],
          live: null,
          github: 'https://github.com/AbdulazizCsDev/carwash-demand-forecast',
        },
      ],
      more: [
        {
          id: 'carwash',
          name: 'نظام إدارة غسيل السيارات',
          desc: 'منصة متكاملة مع إدارة صلاحيات وتتبع طلبات فوري ودمج مدفوعات. مشروع التخرج.',
          tags: ['Flutter', 'PHP', 'MySQL'],
          live: null,
          docs: 'https://car-wash-system-b7mamo4.gamma.site/',
          github: 'https://github.com/AbdulazizCsDev/carwash_system',
        },
        {
          id: 'spy',
          name: 'لعبة الجاسوس متعددة اللاعبين',
          desc: 'لعبة جماعية في الوقت الفعلي مع إدارة غرف ونظام تصويت وإعادة اتصال تلقائية.',
          tags: ['React', 'Node.js', 'Socket.IO'],
          live: 'https://typing-game-client.onrender.com/',
          github: 'https://github.com/AbdulazizCsDev/typing-game',
        },
      ],
    },
    skills: {
      title: 'المهارات',
      categories: [
        {
          name: 'الذكاء التوليدي ونماذج اللغة',
          icon: 'bot',
          skills: ['دمج LLM (OpenAI, Azure OpenAI, Claude)', 'تنسيق وكلاء متعددين', 'RAG (من الصفر)', 'LangChain', 'FAISS', 'ChromaDB', 'التضمينات', 'هندسة الموجهات (DSPy/GEPA)', 'الضبط الدقيق', 'Hugging Face', 'BERT'],
        },
        {
          name: 'تعلّم الآلة والتعلّم العميق',
          icon: 'network',
          skills: ['PyTorch', 'TensorFlow', 'Scikit-learn', 'CNN / نقل التعلم', 'RNN / LSTM / Seq2Seq', 'التنبؤ بالسلاسل الزمنية', 'التقييم وتشخيص الأخطاء'],
        },
        {
          name: 'MLOps والنشر',
          icon: 'rocket',
          skills: ['MLflow', 'ONNX', 'تقديم النماذج عبر FastAPI', 'Docker', 'CI/CD', 'النشر السحابي (HF Spaces, Railway, Render, Vercel)', 'Azure (AI Foundry, OpenAI)', 'AWS (IAM, EC2, S3)'],
        },
        {
          name: 'الباك إند والواجهات البرمجية',
          icon: 'server',
          skills: ['Python', 'FastAPI', 'Flask', 'REST APIs', 'Node.js'],
        },
        {
          name: 'قواعد البيانات',
          icon: 'database',
          skills: ['SQL', 'PostgreSQL (Supabase)', 'MySQL', 'قواعد بيانات متجهة', 'تصميم قواعد البيانات'],
        },
        {
          name: 'الواجهة الأمامية والموبايل',
          icon: 'layout',
          skills: ['React.js', 'Next.js', 'HTML', 'CSS', 'Socket.IO', 'Flutter', 'Dart'],
        },
        {
          name: 'الممارسات واللغات',
          icon: 'code',
          skills: ['ذكاء اصطناعي مسؤول', 'Git وإدارة الإصدارات', 'العربية (أصيل)', 'الإنجليزية (متقدم)'],
        },
      ],
    },
    contact: {
      title: 'لنتواصل',
      subtitle: 'أنا دائماً منفتح على الفرص الجديدة والتعاون والمحادثات المثيرة للاهتمام.',
      email: 'البريد الإلكتروني',
      linkedin: 'لينكدإن',
      github: 'جيت هاب',
      emailVal: 'abdulaziz.alhaidan.cs@gmail.com',
      linkedinVal: 'www.linkedin.com/in/abdulaziz-alhaidan-a902b4232/',
      githubVal: 'github.com/AbdulazizCsDev',
    },
    aime: {
      placeholder: 'اسأل آيم أي شيء...',
      hold: 'اضغط مطولاً للتحدث',
      greeting: 'مرحباً! أنا آيم، مساعد الذكاء الاصطناعي لعبدالعزيز. يمكنني إخبارك عن أعماله ومشاريعه ومهاراته — أو تحليل مدى ملاءمته لوظيفة إن كنت توظّف. كيف أساعدك اليوم؟',
      bubbleGreet: 'أهلاً! هل تحتاج مساعدة؟ يمكنني إخبارك عن أعمال عبدالعزيز!',
      release: 'أرسل بالإفلات...',
      online: 'متصل',
      listening: 'يستمع...',
      thinking: 'يفكر...',
      noBackend: 'عذراً، لم أتمكن من الاتصال بالخادم الآن.',
      noTranscribe: 'تعذّر تحويل الصوت. حاول مرة أخرى.',
      suggestions: [
        { label: 'جولة سريعة', icon: 'target', tour: true },
        {
          label: 'المشاريع',
          query: 'ما هي مشاريعه؟',
          canned: 'هذه مشاريعه — هل يهمّك مشروع محدد؟',
          action: 'projects',
        },
        { label: 'الفوز بالهاكاثون', icon: 'trophy', query: 'أخبرني عن فوز مشروع مجلس الإدارة الذكي بالهاكاثون' },
        { label: 'ملاءمة وظيفية', query: 'أنا مسؤول توظيف. سألصق وصفاً وظيفياً وأريدك أن تحلل مدى ملاءمة عبدالعزيز له — المهارات المطابقة، والمشاريع التي تثبت كل متطلب، والفجوات بصراحة. جاهز؟' },
        {
          label: 'تواصل',
          query: 'كيف أتواصل مع عبدالعزيز؟',
          canned: 'هكذا تصل إليه — البريد أو لينكدإن الأفضل. هل تريد معرفة شيء آخر أولاً؟',
          action: 'contact',
        },
      ],
      tour: [
        { text: 'دعني آخذك في جولة. هذا عبدالعزيز — مهندس ذكاء اصطناعي يصمّم ويبني ويطلق أنظمة LLM وتعلّم آلة من البداية إلى النهاية.', action: 'about' },
        { text: 'مشاريعه. لنبدأ بمجلس الإدارة الذكي — نظام استشاري متعدد الوكلاء حصد المركز الأول في هاكاثون معسكرات همّة الرقمية.', action: 'projects.board-room' },
        { text: 'أجروكيور — كشف أمراض النباتات عبر أكثر من 36 صنفاً، منشور مباشرةً على Hugging Face Spaces، وقد قاد فريقه المكوّن من أربعة مهندسين.', action: 'projects.agrocure' },
        { text: 'وآيم — هذا أنا: Whisper وClaude وElevenLabs، منشور وأحادثك الآن.', action: 'projects.aime' },
        { text: 'العدّة خلف كل ذلك — ذكاء توليدي وتعلّم عميق وMLOps.', action: 'skills' },
        { text: 'وهنا تصل إليه. اسألني ما تشاء — أنا هنا.', action: 'contact' },
      ],
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const toggle = () => setLang((l) => (l === 'en' ? 'ar' : 'en'));
  return (
    <LanguageContext.Provider value={{ lang, toggle, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
